# Generated by Django 5.2.12 on 2026-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_issue_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='digested_log_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='log_quota_exceeded_reason',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='log_quota_exceeded_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='next_log_quota_check',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='retention_max_log_count',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='stored_log_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
