# Generated by Django 5.2.12 on 2026-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonehome', '0005_reset_quota_exceeded_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='log_quota_exceeded_reason',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='installation',
            name='log_quota_exceeded_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='next_log_quota_check',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
