# Generated by Django 5.2.12 on 2026-03-17 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_project_digested_log_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingested_at', models.DateTimeField()),
                ('digested_at', models.DateTimeField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.CharField(blank=True, default='', max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('logger_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_template', models.CharField(blank=True, default='', max_length=1024)),
                ('trace_id', models.CharField(blank=True, default='', max_length=36)),
                ('span_id', models.CharField(blank=True, default='', max_length=32)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('sdk_name', models.CharField(blank=True, default='', max_length=255)),
                ('sdk_version', models.CharField(blank=True, default='', max_length=255)),
                ('release', models.CharField(blank=True, default='', max_length=250)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('sequence', models.BigIntegerField(default=0)),
                ('project_log_order', models.PositiveIntegerField()),
                ('raw_attributes', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'timestamp', 'ingested_at', 'sequence', 'id'], name='logs_logent_project_0b51c1_idx'), models.Index(fields=['project', 'digested_at'], name='logs_logent_project_da8ad4_idx'), models.Index(fields=['digested_at', 'project_log_order'], name='logs_logent_digeste_821f4c_idx'), models.Index(fields=['project', 'project_log_order'], name='logs_logent_project_734433_idx'), models.Index(fields=['project', 'level'], name='logs_logent_project_397ab1_idx'), models.Index(fields=['project', 'logger_name'], name='logs_logent_project_3e19ad_idx'), models.Index(fields=['project', 'trace_id'], name='logs_logent_project_0276a2_idx'), models.Index(fields=['project', 'span_id'], name='logs_logent_project_070574_idx'), models.Index(fields=['project', 'message_template'], name='logs_logent_project_372124_idx'), models.Index(fields=['project', 'origin'], name='logs_logent_project_2c6f8b_idx'), models.Index(fields=['project', 'release'], name='logs_logent_project_9a572f_idx'), models.Index(fields=['project', 'environment'], name='logs_logent_project_a5f400_idx'), models.Index(fields=['project', 'sdk_name'], name='logs_logent_project_b21925_idx'), models.Index(fields=['project', 'sdk_version'], name='logs_logent_project_678f29_idx')],
                'unique_together': {('project', 'project_log_order')},
            },
        ),
    ]
